apiVersion: apps/v1
kind: Deployment
metadata:
  name: decrypt-password-windows-openstack
  namespace: khayangan-dev
spec:
  selector:
    matchLabels:
      run: decrypt-password-windows-openstack
  replicas: 1
  template:
    metadata:
      labels:
        run: decrypt-password-windows-openstack
    spec:
      containers:
        - name: decrypt-password-windows-openstack
          image: registry.carakan.id/khayangan/openstack-decrypt-password-windows:v0.1
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: registry-carakan

---
apiVersion: v1
kind: Service
metadata:
  name: decrypt-password-windows-openstack-service
  namespace: khayangan-dev
spec:
  type: NodePort
  selector:
    run: decrypt-password-windows-openstack
  ports:
    - port: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-decrypt-password-windows-openstack
  namespace: khayangan-dev
spec:
  tls:
    - hosts:
        - decrypt.khayangan.id
      secretName: wildcard-ssl-khayangan-id
  rules:
    - host: decrypt.khayangan.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: decrypt-password-windows-openstack-service
                port:
                  number: 3000
  ingressClassName: nginx
